apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: hello-world-rest-api
      version: v2
    name: hello-world-rest-api-v2
    namespace: default
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: hello-world-rest-api
        version: v2
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: hello-world-rest-api
          version: v2
      spec:
        containers:
        - image: manutd9393/hello-world-rest-api:0.0.2.RELEASE
          imagePullPolicy: IfNotPresent
          name: hello-world-rest-api
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        
---
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: hello-world-rest-api
      version: v1
    name: hello-world-rest-api-v1
    namespace: default
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: hello-world-rest-api
        version: v1
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: hello-world-rest-api
          version: v1
      spec:
        containers:
        - image: manutd9393/hello-world-rest-api:0.0.1.RELEASE
          imagePullPolicy: IfNotPresent
          name: hello-world-rest-api
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        
---
  apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  
  ports:
  - nodePort: 32647
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer
